const state={tab:'scrapbook',page:0,recording:false,seconds:0,steps:0,stepHistory:[0,0,0,0],groups:[{name:'Big Sur Weekend',place:'California Coast',dates:'Jun 14–16',members:4,active:true},{name:'NYC Summer',place:'New York City',dates:'Aug 2–7',members:6,active:true},{name:'Joshua Tree',place:'Mojave Desert',dates:'Apr 19–21',members:3,active:false}],events:[['Carmel coffee walk','Carmel-by-the-Sea','9:30 AM','orange'],['Big Sur hike','Pfeiffer Falls Trail','1:00 PM','teal'],['Sunset dinner','Nepenthe','7:15 PM','pink']],pages:[['Our little<br>escape.','California Coast · Jun 14–16, 2026','cover'],['Day one.','Golden hour on the coast · Jun 14, 2026','sunset'],['The road trip mix.','Photos, notes, and tiny moments','mint']]};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); const tabs=[['groups','♧','Group'],['record','◉','Record'],['scrapbook','▣','Scrapbook'],['calendar','□','Calendar'],['settings','⚙','Settings']];
function renderNav(){ $('#nav').innerHTML=tabs.map(t=>`<button class="${state.tab===t[0]?'active':''}" data-tab="${t[0]}"><span class="nav-icon">${t[1]}</span><span>${t[2]}</span></button>`).join(''); $$('#nav button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab)); }
function showTab(tab){state.tab=tab; $$('.screen').forEach(x=>x.classList.toggle('active',x.id===tab)); $('#pageTitle').textContent=tabs.find(x=>x[0]===tab)[2]; renderNav(); if(tab==='groups')renderGroups(); if(tab==='calendar')renderEvents();}
function renderGroups(){ $('#groupGrid').innerHTML=state.groups.map(g=>`<div class="trip"><div class="trip-top"><span class="trip-icon">${g.active?'✈':'▣'}</span><span class="pill ${g.active?'':'archived'}">${g.active?'Active':'Left'}</span></div><div><h3>${g.name}</h3><p>${g.place} · ${g.dates}</p><p style="margin-top:7px">${g.members} members</p></div></div>`).join(''); }
function renderGroupSelect(){ $('#groupSelect').innerHTML=state.groups.filter(g=>g.active).map(g=>`<option>${g.name}</option>`).join(''); }
function renderBook(){const p=state.pages[state.page];$('#book').className='book '+p[2];$('#bookTitle').innerHTML=p[0];$('#bookSubtitle').textContent=p[1];$('#bookKicker').textContent='Big Sur Weekend · page '+String(state.page+1).padStart(2,'0');$('#pager').innerHTML=state.pages.map((_,i)=>`<span class="dot ${i===state.page?'active':''}"></span>`).join('');}
function renderEvents(){ $('#events').innerHTML=state.events.map(e=>`<div class="event"><span class="event-dot" style="background:${e[3]==='teal'?'#33a99a':e[3]==='pink'?'#e65691':'#fa8a54'}"></span><div><h3>${e[0]}</h3><p>⌖ ${e[1]}</p></div><span class="event-time">${e[2]}</span></div>`).join(''); }
function openModal(html){$('#modal').innerHTML=html;$('#modalBackdrop').classList.add('open');} function closeModal(){$('#modalBackdrop').classList.remove('open')}
function authModal(){openModal(`<div class="modal-head"><h2>Create your private circle</h2><button class="close" data-close>×</button></div><p style="color:var(--muted)">Use an email or phone number to start. This demo is ready to connect to Firebase Auth.</p><div class="field"><label>Email or phone number</label><input id="contact" placeholder="you@example.com"></div><div class="field"><label>Unique handle</label><input id="handle" placeholder="@yourhandle"></div><div class="field"><label>Username <span style="color:var(--muted)">(optional)</span></label><input id="username" placeholder="Your name"></div><div class="field"><label>Password</label><input id="password" type="password" placeholder="8+ characters, letters and numbers"></div><div class="field"><label>Verification code</label><div style="display:flex;gap:8px"><input id="code" inputmode="numeric" maxlength="6" placeholder="6 digits" style="flex:1"><button class="secondary" id="sendCode">Send code</button></div></div><div id="verifyMsg" style="font-size:12px;color:var(--muted);margin-top:8px"></div><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="createAccount">Create account</button></div><div style="border-top:1px solid var(--line);margin-top:20px;padding-top:16px;display:flex;gap:8px"><button class="secondary" style="flex:1"> Apple</button><button class="secondary" style="flex:1">ⓖ Google</button></div>`); bindModal();}
function addMemoryModal(){openModal(`<div class="modal-head"><h2>Add to your scrapbook</h2><button class="close" data-close>×</button></div><p style="color:var(--muted)">Customize this page with a caption, note, location, or media from your photo library.</p><div class="field"><label>Caption / header</label><input id="memoryCaption" placeholder="A moment worth keeping"></div><div class="field"><label>Location</label><input id="memoryLocation" placeholder="Where was this?"></div><div class="field"><label>Page background</label><select id="memoryStyle"><option value="cover">Indigo + rose</option><option value="sunset">Sunset coral</option><option value="mint">Ocean blue</option></select></div><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="saveMemory">Add memory</button></div>`);bindModal();}
function eventModal(){openModal(`<div class="modal-head"><h2>New itinerary event</h2><button class="close" data-close>×</button></div><div class="field"><label>Event name</label><input id="eventName" placeholder="Dinner reservation"></div><div class="field"><label>Location</label><input id="eventLocation" placeholder="Add a location"></div><div class="field"><label>Time</label><input id="eventTime" placeholder="7:00 PM"></div><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="saveEvent">Save event</button></div>`);bindModal();}
function bindModal(){ $$('[data-close]').forEach(b=>b.onclick=closeModal); const send=$('#sendCode'); if(send)send.onclick=()=>$('#verifyMsg').textContent='A unique 6-digit code was sent. Enter it to continue.'; const create=$('#createAccount'); if(create)create.onclick=()=>{const p=$('#password').value,c=$('#code').value;if(p.length<8||!/[A-Za-z]/.test(p)||!/[0-9]/.test(p))return $('#verifyMsg').textContent='Password must be 8+ characters and include letters and numbers.';if(c.length!==6)return $('#verifyMsg').textContent='Enter the 6-digit verification code.';$('#accountButton').textContent='✓';closeModal()}; const save=$('#saveEvent');if(save)save.onclick=()=>{state.events.push([$('#eventName').value||'New plan',$('#eventLocation').value||'Add a location',$('#eventTime').value||'All day','indigo']);closeModal();renderEvents()};const mem=$('#saveMemory');if(mem)mem.onclick=()=>{const title=$('#memoryCaption').value||'A new memory';state.pages[state.page][0]=title;state.pages[state.page][1]=$('#memoryLocation').value||state.pages[state.page][1];state.pages[state.page][2]=$('#memoryStyle').value;renderBook();closeModal()};}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)showTab(b.dataset.tab)});$('#prevPage').onclick=()=>{state.page=(state.page+state.pages.length-1)%state.pages.length;renderBook()};$('#nextPage').onclick=()=>{state.page=(state.page+1)%state.pages.length;renderBook()};$('#historyButton').onclick=()=>$('#history').classList.toggle('open');$('#stepButton').onclick=()=>$('#history').classList.toggle('open');$('#addMemory').onclick=addMemoryModal;$('#addEvent').onclick=eventModal;$('#openAuth').onclick=authModal;$('#accountButton').onclick=authModal;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('#newGroup').onclick=()=>openModal(`<div class="modal-head"><h2>Start a new group</h2><button class="close" data-close>×</button></div><div class="field"><label>Group name</label><input placeholder="Weekend getaway"></div><div class="field"><label>Destination</label><input placeholder="Somewhere memorable"></div><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" data-close>Create group</button></div>`);$('#themeToggle').onclick=()=>{$('#themeToggle').classList.toggle('on');document.body.classList.toggle('dark')};$('#recordButton').onclick=()=>{state.recording=!state.recording;$('#recordButton').classList.toggle('recording',state.recording);$('#recordLabel').textContent=state.recording?'Recording…':'Capture a tiny moment';if(state.recording){state.seconds=0;state.timer=setInterval(()=>{state.seconds++;$('#recordTimer').textContent=state.seconds+'s / 60s';if(state.seconds>=60){state.recording=false;clearInterval(state.timer);$('#recordButton').classList.remove('recording')}},1000)}else{clearInterval(state.timer);$('#recordTimer').textContent='Up to 60 seconds'}};
let touchStart=0;$('#book').addEventListener('touchstart',e=>touchStart=e.changedTouches[0].screenX);$('#book').addEventListener('touchend',e=>{const d=e.changedTouches[0].screenX-touchStart;if(Math.abs(d)>45){state.page=(state.page+(d<0?1:-1)+state.pages.length)%state.pages.length;renderBook()}});document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')$('#nextPage').click();if(e.key==='ArrowLeft')$('#prevPage').click()});renderNav();renderGroupSelect();renderBook();renderGroups();renderEvents();

/* Functional local-first layer: persists scrapbook edits, groups, events, and profile state. */
const savedState=JSON.parse(localStorage.getItem('timecapsule-state')||'null');
if(savedState){Object.assign(state,savedState);$('#groupSelect').value=state.currentGroup||state.groups[0].name;}
// Step counts are intentionally reset for this new account/session.
state.steps=0;state.stepHistory=[0,0,0,0];
state.memories=state.memories||[];
const saveState=()=>localStorage.setItem('timecapsule-state',JSON.stringify({tab:state.tab,page:state.page,groups:state.groups,events:state.events,pages:state.pages,memories:state.memories,currentGroup:state.currentGroup,account:state.account||null,loggedIn:state.loggedIn||false,pendingContact:state.pendingContact||'',pendingHandle:state.pendingHandle||'',pendingUsername:state.pendingUsername||'',pendingPassword:state.pendingPassword||'',steps:0,stepHistory:[0,0,0,0],dark:state.dark||false}));
const renderMemories=()=>{$('.memory-list').innerHTML=(state.memories.length?state.memories.slice(-5).reverse():[{caption:'Golden hour',type:'photo'},{caption:'Roadside flowers',type:'photo'},{caption:'First coffee',type:'note'}]).map(m=>`<div class="memory-item"><div class="thumb">${m.type==='video'?'▶':m.type==='photo'?'◒':'✦'}</div><span>${m.caption}${m.location?' · '+m.location:''}</span></div>`).join('');};
const profileInitials=()=>{const source=(state.account?.username||state.account?.handle||'EC').replace('@','').trim();return source.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'EC';};
const renderProfile=()=>{const account=state.account||{},name=account.username||account.handle||'Eddie Chen',handle=account.handle||'@eddie.travels',initials=profileInitials();['profileAvatar','settingsAvatar','accountButton'].forEach(id=>{if($('#'+id))$('#'+id).textContent=initials});if($('#profileName'))$('#profileName').textContent=name;if($('#profileHandle'))$('#profileHandle').textContent=handle;if($('#settingsName'))$('#settingsName').textContent=name;if($('#settingsHandle'))$('#settingsHandle').textContent=handle;};
const renderSteps=()=>{const values=[0,0,0,0];if($('#stepValue'))$('#stepValue').textContent='0';if($('#stepMetric'))$('#stepMetric').textContent='0';['historyToday','historyYesterday','historyMonday','historySunday'].forEach((id,i)=>{if($('#'+id))$('#'+id).textContent=values[i].toLocaleString()});};
const baseRenderBook=renderBook;
renderBook=()=>{baseRenderBook();const drawing=state.pages[state.page][3];$('#book').style.backgroundImage=drawing?`linear-gradient(135deg,#30246ecc,#7357ee99),url(${drawing})`:'';$('#book').style.backgroundSize='cover';};
const originalAddMemory=addMemoryModal;
addMemoryModal=()=>{openModal(`<div class="modal-head"><h2>Add to your scrapbook</h2><button class="close" data-close>×</button></div><p style="color:var(--muted)">Import a photo or video, then add a caption, note, or location.</p><div class="field"><label>Photo or video</label><input id="memoryFile" type="file" accept="image/*,video/*"></div><div class="field"><label>Caption / header</label><input id="memoryCaption" placeholder="A moment worth keeping"></div><div class="field"><label>Location</label><input id="memoryLocation" placeholder="Where was this?"></div><div class="field"><label>Page background</label><select id="memoryStyle"><option value="cover">Indigo + rose</option><option value="sunset">Sunset coral</option><option value="mint">Ocean blue</option></select></div><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="saveMemory">Add memory</button></div>`);bindModal();$('#saveMemory').onclick=()=>{const file=$('#memoryFile').files[0],caption=$('#memoryCaption').value||'A new memory',location=$('#memoryLocation').value||'';const finish=src=>{state.memories.push({caption,location,type:file?.type.startsWith('video')?'video':'photo',src:src||''});state.pages[state.page][0]=caption;state.pages[state.page][1]=location||state.pages[state.page][1];state.pages[state.page][2]=$('#memoryStyle').value;saveState();renderMemories();renderBook();closeModal()};if(file){const reader=new FileReader();reader.onload=()=>finish(reader.result);reader.readAsDataURL(file)}else finish('');};};
function drawingModal(){openModal(`<div class="modal-head"><h2>Draw on this page</h2><button class="close" data-close>×</button></div><p style="color:var(--muted)">Use your mouse, trackpad, or finger to draw.</p><canvas id="drawingCanvas" width="820" height="420" style="width:100%;height:auto;border-radius:16px;background:#fff;border:1px solid var(--line);touch-action:none"></canvas><div class="modal-actions"><button class="secondary" id="clearDrawing">Clear</button><button class="secondary" data-close>Cancel</button><button class="primary" id="saveDrawing">Save drawing</button></div>`);bindModal();const canvas=$('#drawingCanvas'),ctx=canvas.getContext('2d');ctx.lineWidth=5;ctx.lineCap='round';ctx.strokeStyle='#7357ee';let drawing=false;const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}};canvas.onpointerdown=e=>{drawing=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};canvas.onpointermove=e=>{if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke()};canvas.onpointerup=()=>drawing=false;$('#clearDrawing').onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height);$('#saveDrawing').onclick=()=>{state.pages[state.page][3]=canvas.toDataURL('image/png');state.memories.push({caption:'Hand-drawn note',type:'note'});saveState();renderMemories();renderBook();closeModal()};}
function groupModal(){openModal(`<div class="modal-head"><h2>Start a new group</h2><button class="close" data-close>×</button></div><div class="field"><label>Group name</label><input id="newGroupName" placeholder="Weekend getaway"></div><div class="field"><label>Destination</label><input id="newGroupPlace" placeholder="Somewhere memorable"></div><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="createGroup">Create group</button></div>`);bindModal();$('#createGroup').onclick=()=>{const name=$('#newGroupName').value.trim()||'New group',place=$('#newGroupPlace').value.trim()||'Add a destination';state.groups.push({name,place,dates:'Dates TBD',members:1,active:true});state.currentGroup=name;saveState();renderGroupSelect();renderGroups();closeModal();};}
$('#drawMemory').onclick=drawingModal;$('#addMemory').onclick=addMemoryModal;$('#newGroup').onclick=groupModal;$('#groupSelect').onchange=()=>{state.currentGroup=$('#groupSelect').value;saveState()};
const oldTheme=$('#themeToggle').onclick;$('#themeToggle').onclick=()=>{state.dark=!state.dark;document.body.classList.toggle('dark',state.dark);$('#themeToggle').classList.toggle('on',state.dark);saveState()};if(state.dark){document.body.classList.add('dark');$('#themeToggle').classList.add('on')}
const oldAuth=authModal;authModal=()=>{oldAuth();const oldCreate=$('#createAccount')?.onclick;if(oldCreate)$('#createAccount').onclick=()=>{const handleValue=$('#handle')?.value||'@eddie.travels';oldCreate();if($('#accountButton').textContent==='✓'){state.account={verified:true,handle:handleValue};saveState();}}};
renderGroupSelect();renderMemories();renderBook();renderGroups();renderEvents();renderProfile();renderSteps();saveState();
let mediaRecorder=null,recordedChunks=[];
$('#recordButton').onclick=async()=>{if(state.recording){state.recording=false;clearInterval(state.timer);if(mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();$('#recordButton').classList.remove('recording');$('#recordLabel').textContent='Saved a private vlog';$('#recordTimer').textContent='Video added to Recent memories';return}state.recording=true;state.seconds=0;$('#recordButton').classList.add('recording');$('#recordLabel').textContent='Recording…';$('#recordTimer').textContent='0s / 60s';try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});recordedChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>{if(e.data.size)recordedChunks.push(e.data)};mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(recordedChunks,{type:'video/webm'});state.memories.push({caption:'New private vlog',type:'video',src:URL.createObjectURL(blob)});saveState();renderMemories()};mediaRecorder.start();}catch(e){mediaRecorder=null;$('#recordLabel').textContent='Recording demo mode';}state.timer=setInterval(()=>{state.seconds++;$('#recordTimer').textContent=state.seconds+'s / 60s';if(state.seconds>=60)$('#recordButton').click()},1000)};
const routePages={landing:'landingPage',login:'loginPage','create-account':'createPage',verify:'verifyPage'};
function renderRoute(){let route=(location.hash||'#landing').slice(1)||'landing';if(route==='create')route='create-account';const isApp=route==='app';document.body.classList.toggle('route-app',isApp);document.body.classList.toggle('route-public',!isApp);$('#publicShell').classList.toggle('active',!isApp);Object.values(routePages).forEach(id=>$('#'+id).style.display='none');if(!isApp&&routePages[route])$('#'+routePages[route]).style.display='block';if(isApp){showTab(state.tab||'scrapbook')}if(route==='verify'&&state.pendingContact)$('#verifyCopy').textContent='Enter the six-digit code we sent to '+state.pendingContact+'.';}
function showAuthMessage(id,message){const el=$('#'+id);el.textContent=message;el.classList.add('show')}
$('#loginForm').onsubmit=e=>{e.preventDefault();const contact=$('#loginContact').value.trim(),password=$('#loginPassword').value,account=state.account||{};if(!contact||!password)return showAuthMessage('loginError','Enter both your contact and password.');if(!account.contact)return showAuthMessage('loginError','Create an account first, then log in with those credentials.');if(contact!==account.contact&&contact!==account.handle)return showAuthMessage('loginError','That contact or handle does not match the account.');if(password!==account.password)return showAuthMessage('loginError','That password does not match the account.');state.loggedIn=true;saveState();location.hash='#app'};
$('#createForm').onsubmit=e=>{e.preventDefault();const contact=$('#createContact').value.trim(),handle=$('#createHandle').value.trim(),password=$('#createPassword').value;if(!contact||!handle.startsWith('@'))return showAuthMessage('createError','Enter a contact method and a handle beginning with @.');if(!/^@[A-Za-z0-9._]{3,20}$/.test(handle))return showAuthMessage('createError','Handles may contain letters, numbers, periods, and underscores.');if(password.length<8||!/[A-Za-z]/.test(password)||!/[0-9]/.test(password))return showAuthMessage('createError','Password must be 8+ characters and include letters and numbers.');state.pendingContact=contact;state.pendingHandle=handle;state.pendingUsername=$('#createUsername').value.trim();state.pendingPassword=password;saveState();location.hash='#verify'};
$('#verifyForm').onsubmit=e=>{e.preventDefault();const code=$('#verifyCode').value.trim();if(!/^\d{6}$/.test(code))return showAuthMessage('verifyError','Enter the six-digit verification code.');state.loggedIn=true;state.account={verified:true,contact:state.pendingContact,handle:state.pendingHandle,username:state.pendingUsername,password:state.pendingPassword};delete state.pendingContact;delete state.pendingHandle;delete state.pendingUsername;delete state.pendingPassword;saveState();renderProfile();renderSteps();location.hash='#app'};$('#resendCode').onclick=()=>showAuthMessage('verifyError','A new demo verification code was sent.');$$('[data-provider]').forEach(b=>b.onclick=()=>alert(b.dataset.provider+' sign-in will connect through Firebase in the production version.'));
window.addEventListener('hashchange',renderRoute);if(!location.hash)location.hash='#landing';renderRoute();
